name: Beyond_Sight
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_vision: ^1.1.4
  speech_to_text: ^7.0.0
  highlight_text: ^1.8.0
  avatar_glow: ^3.0.1
  flutter_tts: ^4.0.2
  vibration: ^1.7.4
  permission_handler: ^10.0.0
  shared_preferences: ^2.3.2
  google_fonts: ^4.0.3
  intl: ^0.17.0
  collection: ^1.15.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/beyondsight_logo.png"  # Ensure this is the correct path to your icon

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/ # Add the font directory here

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
